import React, { useState } from "react"
import Category from "./Category.js"

const Categories = ({}) => {
  const [category200, setCategory200] = useState(false)
  const [category400, setCategory400] = useState(false)
  const [category600, setCategory600] = useState(false)
  const [category800, setCategory800] = useState(false)
  const [category1000, setCategory1000] = useState(false)
  const [selectedAnswer, setSelectedAnswer] = useState(false)
  const [incorrectAnswer, setIncorrectAnswer] = useState(false)

  const openCategoryModal = () => {
    setCategory200((prev) => !prev)
    setSelectedAnswer(false)
    setIncorrectAnswer(false)
    console.log("closed")
  }
  return (
    <>
      <div className="categoriesTitle">Configuration & Setup</div>
      <div className="categoriesTitle">
        Object Manager & Lightning App Builder
      </div>
      <div className="categoriesTitle">Sales & Marketing Applications</div>
      <div className="categoriesTitle">Service & Support Applications</div>
      <div className="categoriesTitle">Productivity & Collaboration</div>
      <div className="categoriesTitle">Data & Analytics Management</div>
      <div className="categoriesTitle">Workflow / Process Automation</div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $200
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $200
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $200
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $200
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $200
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $200
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $200
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $400
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $400
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $400
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $400
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $400
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $400
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $400
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $600
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $600
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $600
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $600
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $600
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $600
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $600
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $800
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $800
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $800
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $800
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $800
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $800
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $800
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $1000
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $1000
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $1000
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $1000
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $1000
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $1000
      </div>
      <div
        className="categories"
        category200={category200}
        onClick={openCategoryModal}
      >
        $1000
      </div>
      <Category
        openCategoryModal={openCategoryModal}
        category200={category200}
        selectedAnswer={selectedAnswer}
        setSelectedAnswer={setSelectedAnswer}
        incorrectAnswer={incorrectAnswer}
        setIncorrectAnswer={setIncorrectAnswer}
      />
    </>
  )
}

export default Categories
